// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmupdllswpfyljsaeuyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtdXBkbGxzd3BmeWxqc2FldXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMzYzMzMsImV4cCI6MjA1OTYxMjMzM30.Nrdo-nXfGIySA41w-0CNnybcAosqHFAok10iwZlTBbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);